//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicMonitoring.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicMonitoring.Properties.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Invalid arguments passed.
        ///Would you like to run it in standalone mode?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgArgumentError {
            get {
                return ResourceManager.GetString("MsgArgumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection failed. Please check the input is correct.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgDBConnectFailed {
            get {
                return ResourceManager.GetString("MsgDBConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB settings changed.
        ///The changed settings are applied when you re-execute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgDBSettingsChanged {
            get {
                return ResourceManager.GetString("MsgDBSettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your changes cannot be applied. Please check your changes again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailedConfirmSetting {
            get {
                return ResourceManager.GetString("MsgFailedConfirmSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The input value is invalid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgIncorrectInput {
            get {
                return ResourceManager.GetString("MsgIncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is the largest enlarged size.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgMaximumZoom {
            get {
                return ResourceManager.GetString("MsgMaximumZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It is the smallest size.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgMinimumZoom {
            get {
                return ResourceManager.GetString("MsgMinimumZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to connect to the Mqtt server.
        ///You cannot receive real-time messages.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgMqttError {
            get {
                return ResourceManager.GetString("MsgMqttError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing has changed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNothingChanged {
            get {
                return ResourceManager.GetString("MsgNothingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changes take effect when you restart the program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgSettingChanged {
            get {
                return ResourceManager.GetString("MsgSettingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title changed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgTitleChanged {
            get {
                return ResourceManager.GetString("MsgTitleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Monitoring Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAutoMonitoringMode {
            get {
                return ResourceManager.GetString("StrAutoMonitoringMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCancel {
            get {
                return ResourceManager.GetString("StrCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database Configuration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDatabaseConfig {
            get {
                return ResourceManager.GetString("StrDatabaseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB Host Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDBHostName {
            get {
                return ResourceManager.GetString("StrDBHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDBName {
            get {
                return ResourceManager.GetString("StrDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDBUserName {
            get {
                return ResourceManager.GetString("StrDBUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dynamic Monitoring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDefaultAppTitle {
            get {
                return ResourceManager.GetString("StrDefaultAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEnglish {
            get {
                return ResourceManager.GetString("StrEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Environment setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEnvironmentSetting {
            get {
                return ResourceManager.GetString("StrEnvironmentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrJapanese {
            get {
                return ResourceManager.GetString("StrJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한국어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrKorean {
            get {
                return ResourceManager.GetString("StrKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLanguage {
            get {
                return ResourceManager.GetString("StrLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLayout {
            get {
                return ResourceManager.GetString("StrLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrManagement {
            get {
                return ResourceManager.GetString("StrManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual Monitoring Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrManualMonitoringMode {
            get {
                return ResourceManager.GetString("StrManualMonitoringMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Map과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMap {
            get {
                return ResourceManager.GetString("StrMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMoreOptions {
            get {
                return ResourceManager.GetString("StrMoreOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrOK {
            get {
                return ResourceManager.GetString("StrOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPassword {
            get {
                return ResourceManager.GetString("StrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StrReport과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrReport {
            get {
                return ResourceManager.GetString("StrReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revert Back과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRevertBack {
            get {
                return ResourceManager.GetString("StrRevertBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revert Forward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRevertForward {
            get {
                return ResourceManager.GetString("StrRevertForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server host name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrServerHostName {
            get {
                return ResourceManager.GetString("StrServerHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server&apos;s http port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrServerHttpPort {
            get {
                return ResourceManager.GetString("StrServerHttpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server&apos;s mqtt port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrServerMqttPort {
            get {
                return ResourceManager.GetString("StrServerMqttPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSettings {
            get {
                return ResourceManager.GetString("StrSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSystemDefault {
            get {
                return ResourceManager.GetString("StrSystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning ! ! !과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrWarning {
            get {
                return ResourceManager.GetString("StrWarning", resourceCulture);
            }
        }
    }
}
