//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Module.Management.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMS.Module.Management.Properties.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AlarmTimeStamp과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AlarmTimeStamp {
            get {
                return ResourceManager.GetString("AlarmTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #FFA0A0A0과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorBorder_1 {
            get {
                return ResourceManager.GetString("ColorBorder_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #FF7F50과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorCoral_1 {
            get {
                return ResourceManager.GetString("ColorCoral_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #FF3A3A3A과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorLightBlack_1 {
            get {
                return ResourceManager.GetString("ColorLightBlack_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #FFC5C5C5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorLightGray_1 {
            get {
                return ResourceManager.GetString("ColorLightGray_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #FFDFDFDF과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorLightGray_2 {
            get {
                return ResourceManager.GetString("ColorLightGray_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #FF4500과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorOrangeRed_1 {
            get {
                return ResourceManager.GetString("ColorOrangeRed_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   #FF3500과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ColorRed_1 {
            get {
                return ResourceManager.GetString("ColorRed_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgActiveAction_64x64 {
            get {
                object obj = ResourceManager.GetObject("ImgActiveAction_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgAdd_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgAdd_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgAdd_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgAdd_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgCalculator_64x64 {
            get {
                object obj = ResourceManager.GetObject("ImgCalculator_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgCancel_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgCancel_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgCancel_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgCancel_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgClose_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgClose_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgClose_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgClose_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgCopy_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgCopy_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgCopy_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgCopy_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgDebugging_64x64 {
            get {
                object obj = ResourceManager.GetObject("ImgDebugging_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgDelete_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgDelete_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgDelete_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgDelete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgFailed_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgFailed_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgFind_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgFind_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgFind_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgFind_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgInput_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgInput_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgNext_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgNext_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgNext_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgNext_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgOutput_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgOutput_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgPrevious_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgPrevious_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgPrevious_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgPrevious_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgProperties_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgProperties_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgProperties_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgProperties_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgQuestion_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgRefresh_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgRefresh_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgRefresh_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgRefresh_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgRouting_64x64 {
            get {
                object obj = ResourceManager.GetObject("ImgRouting_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgSave_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgSave_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgSave_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgSave_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgShow_16x16 {
            get {
                object obj = ResourceManager.GetObject("ImgShow_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgShow_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgShow_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgSuccess_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgSuccess_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgUnkownSettings_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgUnkownSettings_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgUnkownSettings_64x64 {
            get {
                object obj = ResourceManager.GetObject("ImgUnkownSettings_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap ImgWatch_32x32 {
            get {
                object obj = ResourceManager.GetObject("ImgWatch_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   You can not change scenario type while editing a scenario.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgCantChangeTypeWhileEdittingScenario {
            get {
                return ResourceManager.GetString("MsgCantChangeTypeWhileEdittingScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The item you are editing can not be deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgCantDeleteEditingItem {
            get {
                return ResourceManager.GetString("MsgCantDeleteEditingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP camera can not be saved while editing an area.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgCantSaveIPCamWhileEdittingArea {
            get {
                return ResourceManager.GetString("MsgCantSaveIPCamWhileEdittingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenarios can not be saved while editing an action.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgCantSaveScenarioWhileEdittingAction {
            get {
                return ResourceManager.GetString("MsgCantSaveScenarioWhileEdittingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenarios can not be saved while editing an sensors.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgCantSaveScenarioWhileEdittingSensorList {
            get {
                return ResourceManager.GetString("MsgCantSaveScenarioWhileEdittingSensorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you change the camera type, you can not use the existing area you set.
        ///Is it ok?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgChangeTypeAreaRemove {
            get {
                return ResourceManager.GetString("MsgChangeTypeAreaRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An area with the same name already exists.
        ///Would you overwrite it?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgDuplicateAreaName {
            get {
                return ResourceManager.GetString("MsgDuplicateAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exceeded maximum text length.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgExceedTextLength {
            get {
                return ResourceManager.GetString("MsgExceedTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to connect to IP camera.
        ///Please check your connection settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailedConnectIPCam {
            get {
                return ResourceManager.GetString("MsgFailedConnectIPCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The deletion request failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailedDeleteReq {
            get {
                return ResourceManager.GetString("MsgFailedDeleteReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load data.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailedLoadData {
            get {
                return ResourceManager.GetString("MsgFailedLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load process list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailedLoadProcessList {
            get {
                return ResourceManager.GetString("MsgFailedLoadProcessList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not get information of the recording file.
        ///Do you want to remove the record from history?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailedLoadRecording {
            get {
                return ResourceManager.GetString("MsgFailedLoadRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get sensor information from the server.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailedLoadSensorInfo {
            get {
                return ResourceManager.GetString("MsgFailedLoadSensorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The request failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailedRequest {
            get {
                return ResourceManager.GetString("MsgFailedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The save request failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFailedSaveReq {
            get {
                return ResourceManager.GetString("MsgFailedSaveReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rutines &apos;{1}&apos; are not compatible with the &apos;{0}&apos; trigger.
        ///Do you want to proceed?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgFormatCheckNotCompatibleRutinesWithTrigger {
            get {
                return ResourceManager.GetString("MsgFormatCheckNotCompatibleRutinesWithTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The input value is invalid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgIncorrectInput {
            get {
                return ResourceManager.GetString("MsgIncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Addition failed. Please make sure that the sensor code is not duplicated and that the data you entered is correct.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgInsertSensorFailed {
            get {
                return ResourceManager.GetString("MsgInsertSensorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted items cannot be recovered. Are you sure you want to delete?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgIsOkRemoveItem {
            get {
                return ResourceManager.GetString("MsgIsOkRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The request is in progress.
        ///Do you want to restart the request?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgIsResumeRequest {
            get {
                return ResourceManager.GetString("MsgIsResumeRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Must be written within 50 characters.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgLimitCharacters {
            get {
                return ResourceManager.GetString("MsgLimitCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modication failed. Please make sure that the sensor code is not duplicated and that the data you entered is correct.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgModifySensorFailed {
            get {
                return ResourceManager.GetString("MsgModifySensorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No items selected.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNotSelectedItem {
            get {
                return ResourceManager.GetString("MsgNotSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please compleate editing item.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgPleaseCompleateEditItem {
            get {
                return ResourceManager.GetString("MsgPleaseCompleateEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please compleate the new action과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgPleaseCompleateNewAction {
            get {
                return ResourceManager.GetString("MsgPleaseCompleateNewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please compleate the new area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgPleaseCompleateNewArea {
            get {
                return ResourceManager.GetString("MsgPleaseCompleateNewArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select action&apos;s type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgPleaseSelectActionsType {
            get {
                return ResourceManager.GetString("MsgPleaseSelectActionsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgPleaseSelectArea {
            get {
                return ResourceManager.GetString("MsgPleaseSelectArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select camera&apos;s type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgPleaseSelectCameraType {
            get {
                return ResourceManager.GetString("MsgPleaseSelectCameraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select ip camera component과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgPleaseSelectIPCamComponent {
            get {
                return ResourceManager.GetString("MsgPleaseSelectIPCamComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select layout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgPleaseSelectLayout {
            get {
                return ResourceManager.GetString("MsgPleaseSelectLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the action properties과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgPleaseSetActionProerties {
            get {
                return ResourceManager.GetString("MsgPleaseSetActionProerties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set trigger.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgPleaseSetTrigger {
            get {
                return ResourceManager.GetString("MsgPleaseSetTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a process.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgProcessDidnSelected {
            get {
                return ResourceManager.GetString("MsgProcessDidnSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a number between 3 and 3600.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgRangeNumError {
            get {
                return ResourceManager.GetString("MsgRangeNumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove failed. Please make sure the sensor has already been deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgRemoveSensorFailed {
            get {
                return ResourceManager.GetString("MsgRemoveSensorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the sensor code.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgSensorCodeDidnEnter {
            get {
                return ResourceManager.GetString("MsgSensorCodeDidnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the sensor name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgSensorNameDidnEnter {
            get {
                return ResourceManager.GetString("MsgSensorNameDidnEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter the code &quot;{0}&quot; for the item to delete it.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgSensorRemove {
            get {
                return ResourceManager.GetString("MsgSensorRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When you refresh, the contents you are currently modifying will disappear.
        ///Do you want to refresh?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgWarningRefresh {
            get {
                return ResourceManager.GetString("MsgWarningRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you control the position of the PTZ camera, It may be disturb other users who are observing the scene with this camera.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgWarnPTZControl {
            get {
                return ResourceManager.GetString("MsgWarnPTZControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flat과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NameIPCameraType_FLAT {
            get {
                return ResourceManager.GetString("NameIPCameraType_FLAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   360° Panorama과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NameIPCameraType_PANO_360 {
            get {
                return ResourceManager.GetString("NameIPCameraType_PANO_360", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PTZ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NameIPCameraType_PTZ {
            get {
                return ResourceManager.GetString("NameIPCameraType_PTZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Increases or Decreases과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Str_RORF_OptionName_BOTH {
            get {
                return ResourceManager.GetString("Str_RORF_OptionName_BOTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only increases과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Str_RORF_OptionName_CLIMB {
            get {
                return ResourceManager.GetString("Str_RORF_OptionName_CLIMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only Decreases과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Str_RORF_OptionName_FALL {
            get {
                return ResourceManager.GetString("Str_RORF_OptionName_FALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abnormal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAbnormal {
            get {
                return ResourceManager.GetString("StrAbnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAccount {
            get {
                return ResourceManager.GetString("StrAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action Detail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionDetail {
            get {
                return ResourceManager.GetString("StrActionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionEdit {
            get {
                return ResourceManager.GetString("StrActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to alarm occurrence layout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionNameAlarmLayout {
            get {
                return ResourceManager.GetString("StrActionNameAlarmLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to camera component과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionNameIPCamComponent {
            get {
                return ResourceManager.GetString("StrActionNameIPCamComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to Layout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionNameLayout {
            get {
                return ResourceManager.GetString("StrActionNameLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action Properties과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionProperties {
            get {
                return ResourceManager.GetString("StrActionProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionSearch {
            get {
                return ResourceManager.GetString("StrActionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionType {
            get {
                return ResourceManager.GetString("StrActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to alarm occurrence layout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionTypeAlarmLayout {
            get {
                return ResourceManager.GetString("StrActionTypeAlarmLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to ip camera component과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionTypeIPCamComponent {
            get {
                return ResourceManager.GetString("StrActionTypeIPCamComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go to Layout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrActionTypeLayout {
            get {
                return ResourceManager.GetString("StrActionTypeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAddArea {
            get {
                return ResourceManager.GetString("StrAddArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAddSensor {
            get {
                return ResourceManager.GetString("StrAddSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm Scenario과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAlarmScenario {
            get {
                return ResourceManager.GetString("StrAlarmScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAlertStateName_0 {
            get {
                return ResourceManager.GetString("StrAlertStateName_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Abnormal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAlertStateName_1 {
            get {
                return ResourceManager.GetString("StrAlertStateName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Danger과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAlertStateName_2 {
            get {
                return ResourceManager.GetString("StrAlertStateName_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stoped과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAlertStateName_900 {
            get {
                return ResourceManager.GetString("StrAlertStateName_900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAll {
            get {
                return ResourceManager.GetString("StrAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrArea {
            get {
                return ResourceManager.GetString("StrArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAreaNameOfNull {
            get {
                return ResourceManager.GetString("StrAreaNameOfNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area registration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAreaRegistration {
            get {
                return ResourceManager.GetString("StrAreaRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAreaSettings {
            get {
                return ResourceManager.GetString("StrAreaSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrBaseTime {
            get {
                return ResourceManager.GetString("StrBaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calc Sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCalcSensor {
            get {
                return ResourceManager.GetString("StrCalcSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCamera {
            get {
                return ResourceManager.GetString("StrCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCameraName {
            get {
                return ResourceManager.GetString("StrCameraName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera orientaion과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCameraOrientation {
            get {
                return ResourceManager.GetString("StrCameraOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCameraSettings {
            get {
                return ResourceManager.GetString("StrCameraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCameraType {
            get {
                return ResourceManager.GetString("StrCameraType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCancel {
            get {
                return ResourceManager.GetString("StrCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Categorical Sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCategoricalSensor {
            get {
                return ResourceManager.GetString("StrCategoricalSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caution과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCaution {
            get {
                return ResourceManager.GetString("StrCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ceiling과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCeiling {
            get {
                return ResourceManager.GetString("StrCeiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCenterValue {
            get {
                return ResourceManager.GetString("StrCenterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comparison value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrComparisonValue {
            get {
                return ResourceManager.GetString("StrComparisonValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Condition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCondition {
            get {
                return ResourceManager.GetString("StrCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Condition result과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrConditionResult {
            get {
                return ResourceManager.GetString("StrConditionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Condition variable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrConditionVariable {
            get {
                return ResourceManager.GetString("StrConditionVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure Actions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrConfigureActions {
            get {
                return ResourceManager.GetString("StrConfigureActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrConnectionSettings {
            get {
                return ResourceManager.GetString("StrConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contents과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrContents {
            get {
                return ResourceManager.GetString("StrContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control Limit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrControlLimit {
            get {
                return ResourceManager.GetString("StrControlLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control Limit Max과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrControlLimitHigh {
            get {
                return ResourceManager.GetString("StrControlLimitHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control Limit Min과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrControlLimitLow {
            get {
                return ResourceManager.GetString("StrControlLimitLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCopy {
            get {
                return ResourceManager.GetString("StrCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comparison과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCountingCondition_COMP {
            get {
                return ResourceManager.GetString("StrCountingCondition_COMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCountingCondition_NONE {
            get {
                return ResourceManager.GetString("StrCountingCondition_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rise or Fall과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCountingCondition_RORF {
            get {
                return ResourceManager.GetString("StrCountingCondition_RORF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZigZag과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCountingCondition_ZIZG {
            get {
                return ResourceManager.GetString("StrCountingCondition_ZIZG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current State과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCurrentState {
            get {
                return ResourceManager.GetString("StrCurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCurrentValue {
            get {
                return ResourceManager.GetString("StrCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Danger과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDanger {
            get {
                return ResourceManager.GetString("StrDanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Decimal Places과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDecimalPlaces {
            get {
                return ResourceManager.GetString("StrDecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera detail settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDetailSettings {
            get {
                return ResourceManager.GetString("StrDetailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDuplicate {
            get {
                return ResourceManager.GetString("StrDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit Sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEditSensor {
            get {
                return ResourceManager.GetString("StrEditSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEndTime {
            get {
                return ResourceManager.GetString("StrEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEquipment1 {
            get {
                return ResourceManager.GetString("StrEquipment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment Detail Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEquipment2 {
            get {
                return ResourceManager.GetString("StrEquipment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEquipmentCode {
            get {
                return ResourceManager.GetString("StrEquipmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEquipmentName {
            get {
                return ResourceManager.GetString("StrEquipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fast과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrFast {
            get {
                return ResourceManager.GetString("StrFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrFlashingStateName_0 {
            get {
                return ResourceManager.GetString("StrFlashingStateName_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fast과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrFlashingStateName_1 {
            get {
                return ResourceManager.GetString("StrFlashingStateName_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrFloor {
            get {
                return ResourceManager.GetString("StrFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenario information is incorrect.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrInfoIncorrect {
            get {
                return ResourceManager.GetString("StrInfoIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrInputTime {
            get {
                return ResourceManager.GetString("StrInputTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inquiry range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrInquiryRange {
            get {
                return ResourceManager.GetString("StrInquiryRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid action과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrInvalidActon {
            get {
                return ResourceManager.GetString("StrInvalidActon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrIPAddress {
            get {
                return ResourceManager.GetString("StrIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Camera과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrIPCam {
            get {
                return ResourceManager.GetString("StrIPCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is use과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrIsUse {
            get {
                return ResourceManager.GetString("StrIsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrItem {
            get {
                return ResourceManager.GetString("StrItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail Keyward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrKeywardDetail {
            get {
                return ResourceManager.GetString("StrKeywardDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search Keyward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrKeywardSearch {
            get {
                return ResourceManager.GetString("StrKeywardSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Month State과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLastMonthState {
            get {
                return ResourceManager.GetString("StrLastMonthState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLayoutSearch {
            get {
                return ResourceManager.GetString("StrLayoutSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left operand과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLeftOperand {
            get {
                return ResourceManager.GetString("StrLeftOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Length과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLength {
            get {
                return ResourceManager.GetString("StrLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tri-color LED alarm settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLightBarTitle {
            get {
                return ResourceManager.GetString("StrLightBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Limit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLimit {
            get {
                return ResourceManager.GetString("StrLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Limit Max과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLimitHigh {
            get {
                return ResourceManager.GetString("StrLimitHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Limit Min과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLimitLow {
            get {
                return ResourceManager.GetString("StrLimitLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modify과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrModify {
            get {
                return ResourceManager.GetString("StrModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitoring scenario과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMonitoringScenario {
            get {
                return ResourceManager.GetString("StrMonitoringScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrNoname {
            get {
                return ResourceManager.GetString("StrNoname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrNumber {
            get {
                return ResourceManager.GetString("StrNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Numerical Sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrNumericalSensor {
            get {
                return ResourceManager.GetString("StrNumericalSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Offset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrOffset {
            get {
                return ResourceManager.GetString("StrOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrOK {
            get {
                return ResourceManager.GetString("StrOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operations과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrOperations {
            get {
                return ResourceManager.GetString("StrOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrOperator {
            get {
                return ResourceManager.GetString("StrOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrOption {
            get {
                return ResourceManager.GetString("StrOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPassword {
            get {
                return ResourceManager.GetString("StrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PMS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPMSType {
            get {
                return ResourceManager.GetString("StrPMSType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPosition {
            get {
                return ResourceManager.GetString("StrPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPrint {
            get {
                return ResourceManager.GetString("StrPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProcess {
            get {
                return ResourceManager.GetString("StrProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProcessCode {
            get {
                return ResourceManager.GetString("StrProcessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProcessName {
            get {
                return ResourceManager.GetString("StrProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StrRange과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRange {
            get {
                return ResourceManager.GetString("StrRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receivers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrReceivers {
            get {
                return ResourceManager.GetString("StrReceivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording target settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRecordingTargetSettings {
            get {
                return ResourceManager.GetString("StrRecordingTargetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Record inquiry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRecordInquiry {
            get {
                return ResourceManager.GetString("StrRecordInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRefresh {
            get {
                return ResourceManager.GetString("StrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove item과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRemoveItem {
            get {
                return ResourceManager.GetString("StrRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove all previous items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRemovePreItem {
            get {
                return ResourceManager.GetString("StrRemovePreItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove Sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRemoveSensor {
            get {
                return ResourceManager.GetString("StrRemoveSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right operand과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRightOperand {
            get {
                return ResourceManager.GetString("StrRightOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Routing Config Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRoutingConfigCode {
            get {
                return ResourceManager.GetString("StrRoutingConfigCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Routing Config Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRoutingConfigName {
            get {
                return ResourceManager.GetString("StrRoutingConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Routing config status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRoutingConfigStatus {
            get {
                return ResourceManager.GetString("StrRoutingConfigStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRun {
            get {
                return ResourceManager.GetString("StrRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running results과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRunningResults {
            get {
                return ResourceManager.GetString("StrRunningResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRunningTime {
            get {
                return ResourceManager.GetString("StrRunningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSave {
            get {
                return ResourceManager.GetString("StrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenario과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrScenario {
            get {
                return ResourceManager.GetString("StrScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenario List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrScenarioList {
            get {
                return ResourceManager.GetString("StrScenarioList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenario Properties과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrScenarioProperties {
            get {
                return ResourceManager.GetString("StrScenarioProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Scenario Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrScenarioSearch {
            get {
                return ResourceManager.GetString("StrScenarioSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sec과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSec {
            get {
                return ResourceManager.GetString("StrSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select an item.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSelectedItem {
            get {
                return ResourceManager.GetString("StrSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Sensors과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSelectSensors {
            get {
                return ResourceManager.GetString("StrSelectSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSensor {
            get {
                return ResourceManager.GetString("StrSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSensorCode {
            get {
                return ResourceManager.GetString("StrSensorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSensorName {
            get {
                return ResourceManager.GetString("StrSensorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensors과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSensors {
            get {
                return ResourceManager.GetString("StrSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measure Unit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSensorUnit {
            get {
                return ResourceManager.GetString("StrSensorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serial Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSerialNumber {
            get {
                return ResourceManager.GetString("StrSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort Order과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSortOrder {
            get {
                return ResourceManager.GetString("StrSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSpeed {
            get {
                return ResourceManager.GetString("StrSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrStartTime {
            get {
                return ResourceManager.GetString("StrStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   State과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrState {
            get {
                return ResourceManager.GetString("StrState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrStop {
            get {
                return ResourceManager.GetString("StrStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subject과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSubject {
            get {
                return ResourceManager.GetString("StrSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTargetSensor {
            get {
                return ResourceManager.GetString("StrTargetSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTest {
            get {
                return ResourceManager.GetString("StrTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTime {
            get {
                return ResourceManager.GetString("StrTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time(sec)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTimeSecond {
            get {
                return ResourceManager.GetString("StrTimeSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Span과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTimeSpan {
            get {
                return ResourceManager.GetString("StrTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Span type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTimeSpanType {
            get {
                return ResourceManager.GetString("StrTimeSpanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTimeSpanTypeName_DAY {
            get {
                return ResourceManager.GetString("StrTimeSpanTypeName_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hour과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTimeSpanTypeName_HOUR {
            get {
                return ResourceManager.GetString("StrTimeSpanTypeName_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minute과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTimeSpanTypeName_MINUTE {
            get {
                return ResourceManager.GetString("StrTimeSpanTypeName_MINUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTimeSpanTypeName_MONTH {
            get {
                return ResourceManager.GetString("StrTimeSpanTypeName_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Second과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTimeSpanTypeName_SECOND {
            get {
                return ResourceManager.GetString("StrTimeSpanTypeName_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Week과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTimeSpanTypeName_WEEK {
            get {
                return ResourceManager.GetString("StrTimeSpanTypeName_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTimeSpanTypeName_YEAR {
            get {
                return ResourceManager.GetString("StrTimeSpanTypeName_YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trigger과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTrigger {
            get {
                return ResourceManager.GetString("StrTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrType {
            get {
                return ResourceManager.GetString("StrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrUser {
            get {
                return ResourceManager.GetString("StrUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrUSERType {
            get {
                return ResourceManager.GetString("StrUSERType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use variables과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrUseVariables {
            get {
                return ResourceManager.GetString("StrUseVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrValue {
            get {
                return ResourceManager.GetString("StrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrVariable {
            get {
                return ResourceManager.GetString("StrVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable name to create과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrVariableName {
            get {
                return ResourceManager.GetString("StrVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wall과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrWall {
            get {
                return ResourceManager.GetString("StrWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning ! ! !과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrWarning {
            get {
                return ResourceManager.GetString("StrWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WorkCenter Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrWorkCenterCode {
            get {
                return ResourceManager.GetString("StrWorkCenterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WorkCenter Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrWorkCenterName {
            get {
                return ResourceManager.GetString("StrWorkCenterName", resourceCulture);
            }
        }
    }
}
