//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.Module.EnvironmentSetting.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMS.Module.EnvironmentSetting.Properties.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Connection failed. Please check the input is correct.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgDBConnectFailed {
            get {
                return ResourceManager.GetString("MsgDBConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB settings changed.
        ///The changed settings are applied when you re-execute.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgDBSettingsChanged {
            get {
                return ResourceManager.GetString("MsgDBSettingsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The input value is invalid.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgIncorrectInput {
            get {
                return ResourceManager.GetString("MsgIncorrectInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The language setting has changed.
        ///Changes made do not take effect until you restart the program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgLanguageChanged {
            get {
                return ResourceManager.GetString("MsgLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing has changed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgNothingChanged {
            get {
                return ResourceManager.GetString("MsgNothingChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The alarm notification settings have been saved.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgSaveAlarmNotiInfo {
            get {
                return ResourceManager.GetString("MsgSaveAlarmNotiInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme settings have been changed.
        ///Changed settings will not take effect until you restart the program.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgThemeChanged {
            get {
                return ResourceManager.GetString("MsgThemeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title changed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MsgTitleChanged {
            get {
                return ResourceManager.GetString("MsgTitleChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAlarm {
            get {
                return ResourceManager.GetString("StrAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alarm notification Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrAlarmNotificationSetting {
            get {
                return ResourceManager.GetString("StrAlarmNotificationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrBasicSetting {
            get {
                return ResourceManager.GetString("StrBasicSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrBlack {
            get {
                return ResourceManager.GetString("StrBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrBlue {
            get {
                return ResourceManager.GetString("StrBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrCancel {
            get {
                return ResourceManager.GetString("StrCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Chart과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrChart {
            get {
                return ResourceManager.GetString("StrChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrClose {
            get {
                return ResourceManager.GetString("StrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Danger과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDangerState {
            get {
                return ResourceManager.GetString("StrDangerState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDatabase {
            get {
                return ResourceManager.GetString("StrDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database Configuration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDatabaseConfig {
            get {
                return ResourceManager.GetString("StrDatabaseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDateTime {
            get {
                return ResourceManager.GetString("StrDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDay {
            get {
                return ResourceManager.GetString("StrDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB Host Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDBHostName {
            get {
                return ResourceManager.GetString("StrDBHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDBName {
            get {
                return ResourceManager.GetString("StrDBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDBPort {
            get {
                return ResourceManager.GetString("StrDBPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDBUserName {
            get {
                return ResourceManager.GetString("StrDBUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dynamic Monitoring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDefaultAppTitle {
            get {
                return ResourceManager.GetString("StrDefaultAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDefaultLanguage {
            get {
                return ResourceManager.GetString("StrDefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Details과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrDetails {
            get {
                return ResourceManager.GetString("StrDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email Address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEmailAddress {
            get {
                return ResourceManager.GetString("StrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEnglish {
            get {
                return ResourceManager.GetString("StrEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Environment setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrEnvironmentSetting {
            get {
                return ResourceManager.GetString("StrEnvironmentSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrFolder {
            get {
                return ResourceManager.GetString("StrFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrForward {
            get {
                return ResourceManager.GetString("StrForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrGeneral {
            get {
                return ResourceManager.GetString("StrGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrHeight {
            get {
                return ResourceManager.GetString("StrHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hour과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrHour {
            get {
                return ResourceManager.GetString("StrHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrImage {
            get {
                return ResourceManager.GetString("StrImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrInsert {
            get {
                return ResourceManager.GetString("StrInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrJapanese {
            get {
                return ResourceManager.GetString("StrJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   한국어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrKorean {
            get {
                return ResourceManager.GetString("StrKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLanguage {
            get {
                return ResourceManager.GetString("StrLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Locale과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLocale {
            get {
                return ResourceManager.GetString("StrLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrLocation {
            get {
                return ResourceManager.GetString("StrLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMail {
            get {
                return ResourceManager.GetString("StrMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMax {
            get {
                return ResourceManager.GetString("StrMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMenu {
            get {
                return ResourceManager.GetString("StrMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMin {
            get {
                return ResourceManager.GetString("StrMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minute과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMinute {
            get {
                return ResourceManager.GetString("StrMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modify과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrModify {
            get {
                return ResourceManager.GetString("StrModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitoring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMonitoring {
            get {
                return ResourceManager.GetString("StrMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrMonth {
            get {
                return ResourceManager.GetString("StrMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrName {
            get {
                return ResourceManager.GetString("StrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navigate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrNavigate {
            get {
                return ResourceManager.GetString("StrNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrNone {
            get {
                return ResourceManager.GetString("StrNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrNormalState {
            get {
                return ResourceManager.GetString("StrNormalState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrOK {
            get {
                return ResourceManager.GetString("StrOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrOpenFile {
            get {
                return ResourceManager.GetString("StrOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPassword {
            get {
                return ResourceManager.GetString("StrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrPrint {
            get {
                return ResourceManager.GetString("StrPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProcess {
            get {
                return ResourceManager.GetString("StrProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProcessCode {
            get {
                return ResourceManager.GetString("StrProcessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProcessName {
            get {
                return ResourceManager.GetString("StrProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Properties과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrProperties {
            get {
                return ResourceManager.GetString("StrProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRefresh {
            get {
                return ResourceManager.GetString("StrRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrRemove {
            get {
                return ResourceManager.GetString("StrRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrReport {
            get {
                return ResourceManager.GetString("StrReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSave {
            get {
                return ResourceManager.GetString("StrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSearch {
            get {
                return ResourceManager.GetString("StrSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSelect {
            get {
                return ResourceManager.GetString("StrSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Backward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSendBackward {
            get {
                return ResourceManager.GetString("StrSendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send to Back과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSendToBack {
            get {
                return ResourceManager.GetString("StrSendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSensor {
            get {
                return ResourceManager.GetString("StrSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSensorCode {
            get {
                return ResourceManager.GetString("StrSensorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSensorName {
            get {
                return ResourceManager.GetString("StrSensorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server host name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrServerHostName {
            get {
                return ResourceManager.GetString("StrServerHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server&apos;s http port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrServerHttpPort {
            get {
                return ResourceManager.GetString("StrServerHttpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server&apos;s mqtt port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrServerMqttPort {
            get {
                return ResourceManager.GetString("StrServerMqttPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSettings {
            get {
                return ResourceManager.GetString("StrSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   State과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrState {
            get {
                return ResourceManager.GetString("StrState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Version과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrSystemVersion {
            get {
                return ResourceManager.GetString("StrSystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TelePhone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTelePhone {
            get {
                return ResourceManager.GetString("StrTelePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTheme {
            get {
                return ResourceManager.GetString("StrTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrTitle {
            get {
                return ResourceManager.GetString("StrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrType {
            get {
                return ResourceManager.GetString("StrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrUnknownState {
            get {
                return ResourceManager.GetString("StrUnknownState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrValue {
            get {
                return ResourceManager.GetString("StrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrVideo {
            get {
                return ResourceManager.GetString("StrVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrView {
            get {
                return ResourceManager.GetString("StrView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning!!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrWarning {
            get {
                return ResourceManager.GetString("StrWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Week과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrWeek {
            get {
                return ResourceManager.GetString("StrWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrWhite {
            get {
                return ResourceManager.GetString("StrWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StrWidth {
            get {
                return ResourceManager.GetString("StrWidth", resourceCulture);
            }
        }
    }
}
